In [1]:
import numpy as np
import math

In [13]:
points = []
points.append([35.658505, 139.802043])
points.append([35.661617, 139.802349])
points.append([35.660445, 139.800450])

points = np.array(points)

In [14]:
points

array([[ 35.658505, 139.802043],
       [ 35.661617, 139.802349],
       [ 35.660445, 139.80045 ]])

In [15]:
_points = points

In [16]:
points = np.delete(points, -1 , 0)

In [17]:
points

array([[ 35.658505, 139.802043],
       [ 35.661617, 139.802349]])

In [18]:
_points = np.delete(_points, 0 , 0)

In [19]:
_points

array([[ 35.661617, 139.802349],
       [ 35.660445, 139.80045 ]])

In [23]:
v = np.c_[points, _points]

In [24]:
v

array([[ 35.658505, 139.802043,  35.661617, 139.802349],
       [ 35.661617, 139.802349,  35.660445, 139.80045 ]])

In [34]:
b1 = np.array(["outputType", "ellipsoid", "latitude1", "longitude1", "latitude2", "longitude2"])

In [35]:
b1

array(['outputType', 'ellipsoid', 'latitude1', 'longitude1', 'latitude2',
       'longitude2'], dtype='<U10')

In [36]:
for point in v:
    point = np.r_[["json", "bessel"], point]
    _v = np.vstack((b1, point))
    _v = _v.transpose()
    _v = dict(_v)
    print(_v)

{'outputType': 'json', 'ellipsoid': 'bessel', 'latitude1': '35.658505', 'longitude1': '139.802043', 'latitude2': '35.661617', 'longitude2': '139.802349'}
{'outputType': 'json', 'ellipsoid': 'bessel', 'latitude1': '35.661617', 'longitude1': '139.802349', 'latitude2': '35.660445', 'longitude2': '139.80045'}


In [37]:
import requests
import json

DISTANCE_API = "http://vldb.gsi.go.jp/sokuchi/surveycalc/surveycalc/bl2st_calc.pl"

In [38]:
def distance(payload):
    r = requests.get(DISTANCE_API, params=payload).json()
    return r['OutputData']['geoLength']  

In [39]:
for point in v:
    point = np.r_[["json", "bessel"], point]
    _v = np.vstack((b1, point))
    _v = _v.transpose()
    _v = dict(_v)
    print(_v)
    print(distance(_v))

{'outputType': 'json', 'ellipsoid': 'bessel', 'latitude1': '35.658505', 'longitude1': '139.802043', 'latitude2': '35.661617', 'longitude2': '139.802349'}
346.358
{'outputType': 'json', 'ellipsoid': 'bessel', 'latitude1': '35.661617', 'longitude1': '139.802349', 'latitude2': '35.660445', 'longitude2': '139.80045'}
215.559


In [44]:
_d = 0
for point in v:
    point = np.r_[["json", "bessel"], point]
    _v = np.vstack((b1, point))
    _v = _v.transpose()
    _v = dict(_v)
    print(_v)
    d = distance(_v)
    print(d)
    _d = _d + float(d)
    
    

{'outputType': 'json', 'ellipsoid': 'bessel', 'latitude1': '35.658505', 'longitude1': '139.802043', 'latitude2': '35.661617', 'longitude2': '139.802349'}
346.358
{'outputType': 'json', 'ellipsoid': 'bessel', 'latitude1': '35.661617', 'longitude1': '139.802349', 'latitude2': '35.660445', 'longitude2': '139.80045'}
215.559


In [45]:
_d

561.917