In [62]:
import numpy as np
from numpy.random import *
import math

In [196]:
count = 3600 * 12

In [197]:
_lo = np.array(rand(count))

In [198]:
_la = _lo**3 

In [199]:
lo = np.sort(_lo + 35) 
la = np.sort(_la + 139)
points_d = np.c_[lo, la]

In [200]:
points_d

array([[ 35.00000577, 139.        ],
       [ 35.00000801, 139.        ],
       [ 35.00004782, 139.        ],
       ...,
       [ 35.99984439, 139.99953324],
       [ 35.99988422, 139.9996527 ],
       [ 35.99993962, 139.99981887]])

In [201]:
_points = points_d
points = points_d

In [202]:
points = np.delete(points, -1 , 0)

In [203]:
points

array([[ 35.00000577, 139.        ],
       [ 35.00000801, 139.        ],
       [ 35.00004782, 139.        ],
       ...,
       [ 35.99981724, 139.99945183],
       [ 35.99984439, 139.99953324],
       [ 35.99988422, 139.9996527 ]])

In [204]:
_points = np.delete(_points, 0 , 0)

In [205]:
_points

array([[ 35.00000801, 139.        ],
       [ 35.00004782, 139.        ],
       [ 35.00005841, 139.        ],
       ...,
       [ 35.99984439, 139.99953324],
       [ 35.99988422, 139.9996527 ],
       [ 35.99993962, 139.99981887]])

In [206]:
v = np.c_[points, _points]

In [207]:
v

array([[ 35.00000577, 139.        ,  35.00000801, 139.        ],
       [ 35.00000801, 139.        ,  35.00004782, 139.        ],
       [ 35.00004782, 139.        ,  35.00005841, 139.        ],
       ...,
       [ 35.99981724, 139.99945183,  35.99984439, 139.99953324],
       [ 35.99984439, 139.99953324,  35.99988422, 139.9996527 ],
       [ 35.99988422, 139.9996527 ,  35.99993962, 139.99981887]])

In [148]:
b1 = np.array(["outputType", "ellipsoid", "latitude1", "longitude1", "latitude2", "longitude2"])

In [149]:
b1

array(['outputType', 'ellipsoid', 'latitude1', 'longitude1', 'latitude2',
       'longitude2'], dtype='<U10')

In [150]:
import requests
import json

DISTANCE_API = "http://vldb.gsi.go.jp/sokuchi/surveycalc/surveycalc/bl2st_calc.pl"

In [134]:
def distance(payload):
    r = requests.get(DISTANCE_API, params=payload).json()
    return r['OutputData']['geoLength']  

In [96]:
_d = 0
for point in v:
    point = np.r_[["json", "bessel"], point]
    _v = np.vstack((b1, point))
    _v = _v.transpose()
    _v = dict(_v)
    print(_v)
    d = distance(_v)
    print(d)
    _d = _d + float(d)
    
    

{'outputType': 'json', 'ellipsoid': 'bessel', 'latitude1': '35.00014737562787', 'longitude1': '139.00025634071227', 'latitude2': '35.00027018386516', 'longitude2': '139.00037457491968'}
17.380
{'outputType': 'json', 'ellipsoid': 'bessel', 'latitude1': '35.00027018386516', 'longitude1': '139.00037457491968', 'latitude2': '35.0002719529474', 'longitude2': '139.00056925910528'}
17.771
{'outputType': 'json', 'ellipsoid': 'bessel', 'latitude1': '35.0002719529474', 'longitude1': '139.00056925910528', 'latitude2': '35.000312262043224', 'longitude2': '139.00065491575123'}
9.007
{'outputType': 'json', 'ellipsoid': 'bessel', 'latitude1': '35.000312262043224', 'longitude1': '139.00065491575123', 'latitude2': '35.00090981782909', 'longitude2': '139.0006793367047'}
66.324
{'outputType': 'json', 'ellipsoid': 'bessel', 'latitude1': '35.00090981782909', 'longitude1': '139.0006793367047', 'latitude2': '35.00105578370231', 'longitude2': '139.00081363514062'}
20.309
{'outputType': 'json', 'ellipsoid': 'b

KeyboardInterrupt: 

In [97]:
_d

499.97799999999995

In [208]:
import folium
import numpy as np
import math

points = np.array(points_d)
location = [( np.max(points[:,0]) + np.min(points[:,0]) ) / 2, ( np.max(points[:,1]) + np.min(points[:,1]) ) / 2]

width = np.max([( np.max(points[:,0]) - np.min(points[:,0]) ),  ( np.max(points[:,1]) - np.min(points[:,1]) )])

points = points.tolist()

x = width

zoom = math.log(5*x/9500, 0.5)

m = folium.Map(location=location, zoom_start=zoom)
folium.PolyLine(points).add_to(m)
m
