In [56]:
import numpy as np
from numpy.random import *
import math
import time


def hubeny(latf, longf, late, longe):
    y1 = latf
    y2 = late
    x1 = longf
    x2 = longe

    a = 6378137.0
    b = 6356752.314140
    dy = math.radians(y2 - y1)
    dx = math.radians(x2 - x1)
    my = math.radians((y1 + y2) / 2)
    e2 = (a**2 - b**2) / a**2
    Mnum = a * (1 - e2)
    W = math.sqrt(1 - e2 * math.sin(my)**2)
    M = Mnum / W**3
    N = a / W
    return math.sqrt((dy * M)**2 + (dx * N * math.cos(my))**2)


In [57]:
count = 3601 * 24
_lo = np.array(rand(count))
_la = _lo**3 

lo = np.sort(_lo + 35) 
la = np.sort(_la + 139)
points = np.c_[lo, la]

In [58]:
points

array([[ 35.00000383, 139.        ],
       [ 35.0000163 , 139.        ],
       [ 35.00002055, 139.        ],
       ...,
       [ 35.99995742, 139.99987226],
       [ 35.99996693, 139.99990079],
       [ 35.99997037, 139.99991112]])

In [59]:
v = np.c_[np.delete(points, -1 , 0), np.delete(points, 0 , 0)]
v

array([[ 35.00000383, 139.        ,  35.0000163 , 139.        ],
       [ 35.0000163 , 139.        ,  35.00002055, 139.        ],
       [ 35.00002055, 139.        ,  35.00002966, 139.        ],
       ...,
       [ 35.99994733, 139.99984199,  35.99995742, 139.99987226],
       [ 35.99995742, 139.99987226,  35.99996693, 139.99990079],
       [ 35.99996693, 139.99990079,  35.99997037, 139.99991112]])

In [60]:
v.shape

(86423, 4)

In [61]:
start = time.time()
distance = 0
for point in v:
    distance += hubeny(point[0], point[1], point[2], point[3])

print(distance)
elapsed_time = time.time() - start
print ("elapsed_time:{0}".format(elapsed_time) + "[sec]")

155587.642726857
elapsed_time:0.2534909248352051[sec]


In [62]:
v[:,1]

array([139.        , 139.        , 139.        , ..., 139.99984199,
       139.99987226, 139.99990079])

In [63]:
def hubeny(latf, longf, late, longe):
    y1 = latf
    y2 = late
    x1 = longf
    x2 = longe

    a = 6378137.0
    b = 6356752.314140
    dy = np.radians(y2 - y1)
    dx = np.radians(x2 - x1)
    my = np.radians((y1 + y2) / 2)
    e2 = (a**2 - b**2) / a**2
    Mnum = a * (1 - e2)
    W = np.sqrt(1 - e2 * np.sin(my)**2)
    M = Mnum / W**3
    N = a / W
    return np.sqrt((dy * M)**2 + (dx * N * np.cos(my))**2)


In [64]:
start = time.time()

distances = hubeny(v[:,0], v[:,1], v[:,2], v[:,3])
print(np.sum(distances))

elapsed_time = time.time() - start
print ("elapsed_time:{0}".format(elapsed_time) + "[sec]")

155587.6427268551
elapsed_time:0.012278079986572266[sec]
