In [82]:
import numpy as np
from numpy.random import *
import math
import time


def hubeny(latf, longf, late, longe):
    y1 = latf
    y2 = late
    x1 = longf
    x2 = longe

    a = 6378137.0
    b = 6356752.314140
    dy = math.radians(y2 - y1)
    dx = math.radians(x2 - x1)
    my = math.radians((y1 + y2) / 2)
    e2 = (a**2 - b**2) / a**2
    Mnum = a * (1 - e2)
    W = math.sqrt(1 - e2 * math.sin(my)**2)
    M = Mnum / W**3
    N = a / W
    return math.sqrt((dy * M)**2 + (dx * N * math.cos(my))**2)


In [83]:
count = 3601 * 24
_lo = np.array(rand(count))
_la = _lo**3 

lo = np.sort(_lo + 35) 
la = np.sort(_la + 139)
points = np.c_[lo, la]

In [84]:
points

array([[ 35.00000752, 139.        ],
       [ 35.00000991, 139.        ],
       [ 35.00001077, 139.        ],
       ...,
       [ 35.99995162, 139.99985487],
       [ 35.99997974, 139.99993921],
       [ 35.99999853, 139.99999558]])

In [85]:
v = np.c_[np.delete(points, -1 , 0), np.delete(points, 0 , 0)]
v

array([[ 35.00000752, 139.        ,  35.00000991, 139.        ],
       [ 35.00000991, 139.        ,  35.00001077, 139.        ],
       [ 35.00001077, 139.        ,  35.00004057, 139.        ],
       ...,
       [ 35.99994833, 139.99984501,  35.99995162, 139.99985487],
       [ 35.99995162, 139.99985487,  35.99997974, 139.99993921],
       [ 35.99997974, 139.99993921,  35.99999853, 139.99999558]])

In [86]:
v.shape

(86423, 4)

In [87]:
start = time.time()
distance = 0
for point in v:
    distance += hubeny(point[0], point[1], point[2], point[3])

print(distance)
elapsed_time = time.time() - start
print ("elapsed_time:{0}".format(elapsed_time) + "[sec]")

155595.46489706112
elapsed_time:0.25295305252075195[sec]


In [88]:
v[:,1]

array([139.        , 139.        , 139.        , ..., 139.99984501,
       139.99985487, 139.99993921])

In [89]:
def hubeny(latf, longf, late, longe):
    y1 = latf
    y2 = late
    x1 = longf
    x2 = longe

    a = 6378137.0
    b = 6356752.314140
    dy = np.radians(y2 - y1)
    dx = np.radians(x2 - x1)
    my = np.radians((y1 + y2) / 2)
    e2 = (a**2 - b**2) / a**2
    Mnum = a * (1 - e2)
    W = np.sqrt(1 - e2 * np.sin(my)**2)
    M = Mnum / W**3
    N = a / W
    return np.sqrt((dy * M)**2 + (dx * N * np.cos(my))**2)


In [90]:
start = time.time()

distances = hubeny(v[:,0], v[:,1], v[:,2], v[:,3])
print(np.sum(distances))

elapsed_time = time.time() - start
print ("elapsed_time:{0}".format(elapsed_time) + "[sec]")

155595.46489706245
elapsed_time:0.006199836730957031[sec]


In [91]:
v = np.array([[35, 139, 55, 159]])

In [92]:
def hubeny(latf, longf, late, longe):
    y1 = latf
    y2 = late
    x1 = longf
    x2 = longe

    a = 6378137.0
    b = 6356752.314140
    dy = math.radians(y2 - y1)
    dx = math.radians(x2 - x1)
    my = math.radians((y1 + y2) / 2)
    e2 = (a**2 - b**2) / a**2
    Mnum = a * (1 - e2)
    W = math.sqrt(1 - e2 * math.sin(my)**2)
    M = Mnum / W**3
    N = a / W
    return math.sqrt((dy * M)**2 + (dx * N * math.cos(my))**2)


In [93]:
distance = 0
for point in v:
    distance += hubeny(point[0], point[1], point[2], point[3])

print(distance)


2725222.585805935


In [94]:
def hubeny(latf, longf, late, longe):
    y1 = latf
    y2 = late
    x1 = longf
    x2 = longe

    a = 6378137.0
    b = 6356752.314140
    dy = np.radians(y2 - y1)
    dx = np.radians(x2 - x1)
    my = np.radians((y1 + y2) / 2)
    e2 = (a**2 - b**2) / a**2
    Mnum = a * (1 - e2)
    W = np.sqrt(1 - e2 * np.sin(my)**2)
    M = Mnum / W**3
    N = a / W
    return np.sqrt((dy * M)**2 + (dx * N * np.cos(my))**2)


In [95]:
start = time.time()

distances = hubeny(v[:,0], v[:,1], v[:,2], v[:,3])
print(np.sum(distances))

elapsed_time = time.time() - start
print ("elapsed_time:{0}".format(elapsed_time) + "[sec]")

2725222.585805935
elapsed_time:0.00039315223693847656[sec]


In [96]:
a = 6378137.0
b = 6356752.314140
e2 = (a**2 - b**2) / a**2
Mnum = a * (1 - e2)
Mnum

6335439.327083167

In [97]:
e2

0.00669438002301188

In [108]:
def hubeny(latf, longf, late, longe):
    a = 6378137.0
    e2 = 0.00669438002301188
    Mnum = 6335439.327083167

    dy = np.radians(late - latf)
    dx = np.radians(longe - longf)
    my = np.radians((latf + late) / 2)
    W = np.sqrt(1 - e2 * np.sin(my)**2)
    M = Mnum / W**3
    N = a / W
    return np.sqrt((dy * M)**2 + (dx * N * np.cos(my))**2)

In [109]:
start = time.time()

distances = hubeny(v[:,0], v[:,1], v[:,2], v[:,3])
print(np.sum(distances))

elapsed_time = time.time() - start
print ("elapsed_time:{0}".format(elapsed_time) + "[sec]")

2725222.585805935
elapsed_time:0.0003178119659423828[sec]
